export default {
  NUMBER: "[object Number]",
  STRING: "[object String]",
  BOOLEAN: "[object Boolean]",
  UNDEFINED: "[object Undefined]",
  NULL: "[object Null]",
  OBJECT: "[object Object]",
  ARRAY: "[object Array]",
  SYMBOL: "[object Symbol]",
  DATE: "[object Date]",
  REGEXP: "[object RegExp]",
  BIGINT: "[object BigInt]",
  FUNCTION: "[object Function]",
  BLOB: "[object Blob]",
  FILE: "[object File]",
};
